services:
  database:
    image: postgresql:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=laundry_api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - lavi_data:/var/lib/postgresql/data
  api:
    build:
      context: .
    env_file: .env.prod
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://root:root@database:5432/laundry_api
    depends_on:
      database:
        condition: service_healthy
volumes:
  lavi_data:
