services:
  database:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=laundry_api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      database:
        condition: service_healthy
