ALTER TABLE "employee" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee" ALTER COLUMN "cpf_blind_index" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee" ALTER COLUMN "cpf" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee" ALTER COLUMN "email_blind_index" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee" ALTER COLUMN "email" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee" ALTER COLUMN "password" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee" ALTER COLUMN "laundryId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "order" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "order" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "order" ALTER COLUMN "delivery_type" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "order" ALTER COLUMN "details" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "order" ALTER COLUMN "latitude" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "order" ALTER COLUMN "longitude" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "order" ALTER COLUMN "laundryId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "order" ALTER COLUMN "customerId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "orderItem" ALTER COLUMN "qntd" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "orderItem" ALTER COLUMN "unitPrice_inCents" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "orderItem" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "orderItem" ALTER COLUMN "service" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "orderItem" ALTER COLUMN "orderId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "laundry" ADD COLUMN "putEmployeeCode" text;